apiVersion: v1
kind: Service
metadata:
  name: library-api-service
  labels:
    app: library-api
spec:
  type: LoadBalancer
  selector:
    app: library-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  sessionAffinity: None